name: Deploy to Dev Server

on:
  workflow_dispatch:

  push:
    branches:
      - dev
    paths:
      - "server/**"
      - ".github/workflows/server_ci.yml"

jobs:
  deploy:
    name: Deploy to Dev Server
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Rsync Deployment
        run: rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./server ubuntu@$SERVER_HOST:/home/ubuntu/real-time-chat

      - name: Run Deploy Script
        run: ssh -v -i ~/.ssh/id_rsa ubuntu@$SERVER_HOST "/home/ubuntu/real-time-chat/deploy.sh"
